version: "3.9"
services:
  api:
    container_name: api-ratings
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"

  tests-ratings:
    container_name: tests-api-ratings
    build:
        context: tests/ratings
        dockerfile: DockerfileRatingsTests
    image: tests-api-ratings:latest
    network_mode: host

  tests-performances:
    container_name: tests-api-performances
    build:
        context: tests/performances
        dockerfile: DockerfilePerformancesTests
    image: tests-api-performances:latest
    network_mode: host